# Multiple player Quantum Prisoner's Dilemma

## Import

In [1]:
import numpy as np
import pandas as pd
from solver import find_nash_eq1, kick_with_u, compute_four_qubit_SLOCC_invariants
from game import get_default_4players, get_default_H
from mps_utils import get_rand_mps, get_ghz_state, to_canonical_form, to_comp_basis

import time
from tqdm import tqdm

Using CPU


## NE for 3 players on GHZ orbits

Looking at the amplitudes, the new family of NEs are not related to previous ones 

In [ ]:
state_0 = get_ghz_state(L=3)
H = get_default_H(num_players=3, option='H', dtype=np.float32)
results = []

for i in tqdm(range(10)):
    state = kick_with_u(state_0)
    state = to_canonical_form(state)
    result = find_nash_eq1(Psi=state, H=H, max_iter=1000, alpha=0.06, convergence_threshold=1e-6, expl_threshold=1e-3, use_tqdm=True, expl_check_interval=30, return_history=False)
    results.append(result)


In [4]:
energies = np.array([result['energy'] for result in results])
print(energies)

[[4.866 4.5   4.633]
 [4.623 4.5   4.876]
 [4.957 4.54  4.502]
 [4.901 4.597 4.501]
 [4.717 4.782 4.5  ]
 [4.825 4.5   4.674]
 [4.819 4.68  4.5  ]
 [4.975 4.518 4.506]
 [4.694 4.5   4.805]
 [4.506 4.518 4.975]]


In [7]:
states = np.array([result['state'].reshape(-1) for result in results])
print(states)


[[-0.014 -0.366  0.023  0.605 -0.605  0.023 -0.366  0.014]
 [-0.026 -0.613  0.009 -0.351 -0.35   0.027  0.614 -0.005]
 [-0.014  0.049 -0.201  0.676 -0.676 -0.201  0.049  0.014]
 [-0.013  0.026  0.312 -0.634 -0.634 -0.312 -0.026 -0.013]
 [ 0.008  0.02  -0.531 -0.466 -0.466  0.531 -0.006  0.021]
 [ 0.011 -0.417 -0.019  0.57  -0.57  -0.016 -0.417 -0.015]
 [ 0.013 -0.022 -0.425  0.565  0.565  0.424  0.019  0.018]
 [-0.016  0.079 -0.136  0.689 -0.689 -0.136  0.079  0.016]
 [ 0.003 -0.553 -0.024  0.44   0.441 -0.002  0.552  0.024]
 [-0.015  0.689  0.136  0.076  0.076  0.136 -0.689  0.015]]
